In [1]:
from scipy.io import loadmat
ocr = loadmat('ocr.mat')
import matplotlib.pyplot as plt
from matplotlib import cm
import numpy as np
import random
import time

In [2]:
def checking(preds,ocr):
    check3 = (preds.astype(np.int8)) - (ocr['testlabels'].astype(np.int8))
    error = (np.sum(check3.astype(np.bool)))/len(preds)
    return error

In [3]:
def randomsampling(ocr,n, iterations,errormatrix):
    for i in n:
        for a in range(iterations):
            sel = random.sample(range(60000),i)
            dataR = np.array(ocr['data'][sel].astype('float'))
            labelsR = np.array(ocr['labels'][sel])
            preds = functionProblem1(dataR,labelsR,ocr['testdata'])
            error = checking(preds,ocr)
            errormatrix.append(error)
    return errormatrix   

In [4]:
def functionProblem1(dataR,labelsR,testdata):
    dataR = dataR.astype(np.float64)
    test2 = np.array(testdata).astype(np.float64)
    base = (-2)*(np.dot(dataR,test2.T)) + np.vstack(np.sum(np.square(dataR),axis=1))
    base = np.sqrt(base.T + np.vstack(np.sum(np.square(test2),axis=1)))
    preds = labelsR[np.argmin(base,axis=1)]
    return preds

In [5]:
start_time = time.time()

n = [1000, 2000, 4000, 8000]
iterations = 10
errormatrix=[]

errormatrix = randomsampling(ocr,n,iterations,errormatrix)

errormatrix = np.reshape(np.array(errormatrix),(len(n),iterations)).T
stderror = np.std(errormatrix,axis=0)
meanerror =  np.mean(errormatrix, axis=0)
print("Error Matrix")
print(n)
print(errormatrix)
print("Standard Errors")
print(stderror)
print("Sample means")
print(meanerror)
plt.errorbar(n,meanerror,stderror)
plt.axis([0,10000,0,0.15])
print("--- %s seconds ---" % (time.time() - start_time))
plt.show()

Error Matrix
[1000, 2000, 4000, 8000]
[[ 0.1159  0.0854  0.0702  0.0547]
 [ 0.1091  0.0887  0.0697  0.056 ]
 [ 0.119   0.0873  0.0743  0.055 ]
 [ 0.1176  0.0883  0.0659  0.0554]
 [ 0.1169  0.088   0.0736  0.0577]
 [ 0.122   0.091   0.0669  0.055 ]
 [ 0.1149  0.091   0.0654  0.0533]
 [ 0.1152  0.0907  0.0688  0.056 ]
 [ 0.123   0.0824  0.0732  0.0546]
 [ 0.1118  0.0939  0.0695  0.0563]]
Standard Errors
[ 0.0040195   0.00307898  0.00300774  0.00112606]
Sample means
[ 0.11654  0.08867  0.06975  0.0554 ]
--- 451.4218068122864 seconds ---
