In [1]:
from scipy.io import loadmat
from scipy import stats
ocr = loadmat('ocr.mat')
import matplotlib.pyplot as plt
from matplotlib import cm
import numpy as np
import random
import time

In [2]:
def getselection(labelfreq,m,iterations):    
    for sample in m:
        for j in range(iterations):       
            a=0
            newsel=[]
            n = int(sample/10)
            #10 iterations for 10 digits
            for i in range(10):
                sel= random.sample(list(np.arange(a,(labelfreq[i][1]-1+a))),  n)
                newsel.append(sel)
                a= a+(labelfreq[i][1])
            newsel = np.ravel(np.array(newsel))
            newdata = datalabels[newsel,1:785]
            newlabels = datalabels[newsel,0]
            preds = functionProblem1(newdata,newlabels,ocr['testdata'])
            error = checking(preds,ocr)
            errormatrix.append(error)      
    return errormatrix

In [3]:
def functionProblem1(dataR,labelsR,testdata):
    dataR = dataR.astype(np.float64)
    test2 = np.array(testdata).astype(np.float64)
    base = (-2)*(np.dot(dataR,test2.T)) + np.vstack(np.sum(np.square(dataR),axis=1))
    base = np.sqrt(base.T + np.vstack(np.sum(np.square(test2),axis=1)))
    preds = labelsR[np.argmin(base,axis=1)]
    return preds

In [4]:
def checking(preds,ocr):
    check3 = (np.vstack(preds.astype(np.int8))) - (ocr['testlabels'].astype(np.int8))
    error = (np.sum(check3.astype(np.bool)))/len(preds)
    return error

In [5]:
start_time = time.time()

m = [1000, 2000, 4000, 8000]
iterations = 10
errormatrix=[]

labelfreq = np.array(stats.itemfreq(ocr['labels']))
datalabels = (np.concatenate((np.array(ocr['labels']),np.array(ocr['data'])), axis=1)).astype(np.float64)
datalabels = datalabels[np.argsort(datalabels[:,0])]

errormatrix = getselection(labelfreq, m, iterations)

errormatrix = np.reshape(np.array(errormatrix),(len(m),iterations)).T
stderror = np.std(errormatrix,axis=0)
meanerror =  np.mean(errormatrix, axis=0)

print("Error Matrix")
print(m)
print(errormatrix)
print("Standard Errors")
print(stderror)
print("Sample means")
print(meanerror)
plt.errorbar(m,meanerror,stderror)
plt.axis([0,10000,0,0.15])
print("--- %s seconds ---" % (time.time() - start_time))
plt.show()

Error Matrix
[1000, 2000, 4000, 8000]
[[ 0.1072  0.0807  0.0691  0.0562]
 [ 0.1156  0.0855  0.0675  0.0563]
 [ 0.109   0.0852  0.0713  0.0554]
 [ 0.1127  0.0902  0.067   0.0562]
 [ 0.1178  0.0853  0.0671  0.0533]
 [ 0.1133  0.0857  0.0691  0.0554]
 [ 0.1212  0.0856  0.067   0.0531]
 [ 0.1113  0.083   0.0729  0.0554]
 [ 0.1139  0.0848  0.0731  0.0578]
 [ 0.1088  0.0868  0.0684  0.0538]]
Standard Errors
[ 0.00410044  0.00230773  0.00225666  0.00141382]
Sample means
[ 0.11308  0.08528  0.06925  0.05529]
--- 481.6837315559387 seconds ---


In [6]:
labelfreq = np.array(stats.itemfreq(ocr['labels']))
print(labelfreq)

[[   0 5923]
 [   1 6742]
 [   2 5958]
 [   3 6131]
 [   4 5842]
 [   5 5421]
 [   6 5918]
 [   7 6265]
 [   8 5851]
 [   9 5949]]
